import { ProductModel } from '@/types/productModel'

export const products: ProductModel[] = [
  {
    id: '1',
    name: 'MacBook Pro 16" M3 Max',
    price: 3499,
    category: 'Laptops',
    description:
      'El portátil más potente de Apple con chip M3 Max, pantalla Liquid Retina XDR de 16 pulgadas y hasta 22 horas de batería.',
    images: [
      '/macbook-pro-16-silver-front-view.jpg',
      '/macbook-pro-16-silver-side-angle.jpg',
      '/macbook-pro-16-keyboard-closeup.jpg',
      '/macbook-pro-16-ports-detail.jpg',
    ],
    specs: [
      { label: 'Procesador', value: 'Apple M3 Max' },
      { label: 'RAM', value: '36GB Unified Memory' },
      { label: 'Almacenamiento', value: '1TB SSD' },
      { label: 'Pantalla', value: '16.2" Liquid Retina XDR' },
    ],
    rating: 4.8,
    reviews: 1247,
    inStock: true,
  },
  {
    id: '2',
    name: 'iPhone 15 Pro Max',
    price: 1199,
    category: 'Smartphones',
    description:
      'El iPhone más avanzado con titanio aeroespacial, chip A17 Pro y cámara de 48MP con zoom óptico 5x.',
    images: [
      '/iphone-15-pro-max-titanium-blue-front.jpg',
      '/iphone-15-pro-max-back-camera-system.jpg',
      '/iphone-15-pro-max-side-profile.jpg',
      '/iphone-15-pro-max-action-button.jpg',
    ],
    specs: [
      { label: 'Chip', value: 'A17 Pro' },
      { label: 'Pantalla', value: '6.7" Super Retina XDR' },
      { label: 'Cámara', value: '48MP Principal + 12MP Ultra Wide' },
      { label: 'Almacenamiento', value: '256GB' },
    ],
    rating: 4.9,
    reviews: 3421,
    inStock: true,
  },
  {
    id: '3',
    name: 'Sony WH-1000XM5',
    price: 399,
    category: 'Audio',
    description:
      'Auriculares premium con cancelación de ruido líder en la industria y calidad de sonido excepcional.',
    images: [
      '/sony-wh1000xm5-black-headphones-front.jpg',
      '/sony-wh1000xm5-side-view-folded.jpg',
      '/sony-wh1000xm5-ear-cup-detail.jpg',
      '/sony-wh1000xm5-with-case.jpg',
    ],
    specs: [
      { label: 'Cancelación de ruido', value: 'Activa HD' },
      { label: 'Batería', value: 'Hasta 30 horas' },
      { label: 'Conectividad', value: 'Bluetooth 5.2' },
      { label: 'Audio', value: 'Hi-Res Audio' },
    ],
    rating: 4.7,
    reviews: 892,
    inStock: true,
  },
  {
    id: '4',
    name: 'iPad Pro 12.9" M2',
    price: 1099,
    category: 'Tablets',
    description:
      'La tablet más avanzada con chip M2, pantalla Liquid Retina XDR y compatibilidad con Apple Pencil.',
    images: [
      '/ipad-pro-12-9-space-gray-front.jpg',
      '/ipad-pro-with-apple-pencil.jpg',
      '/ipad-pro-back-camera.jpg',
      '/placeholder.svg?height=600&width=600',
    ],
    specs: [
      { label: 'Chip', value: 'Apple M2' },
      { label: 'Pantalla', value: '12.9" Liquid Retina XDR' },
      { label: 'Almacenamiento', value: '256GB' },
      { label: 'Conectividad', value: '5G + Wi-Fi 6E' },
    ],
    rating: 4.8,
    reviews: 654,
    inStock: true,
  },
  {
    id: '5',
    name: 'Samsung Galaxy S24 Ultra',
    price: 1299,
    category: 'Smartphones',
    description:
      'Smartphone insignia con S Pen integrado, cámara de 200MP y pantalla Dynamic AMOLED 2X.',
    images: [
      '/placeholder.svg?height=600&width=600',
      '/placeholder.svg?height=600&width=600',
      '/placeholder.svg?height=600&width=600',
      '/placeholder.svg?height=600&width=600',
    ],
    specs: [
      { label: 'Procesador', value: 'Snapdragon 8 Gen 3' },
      { label: 'RAM', value: '12GB' },
      { label: 'Cámara', value: '200MP Principal' },
      { label: 'Batería', value: '5000mAh' },
    ],
    rating: 4.7,
    reviews: 2103,
    inStock: true,
  },
  {
    id: '6',
    name: 'Dell XPS 15',
    price: 1899,
    category: 'Laptops',
    description:
      'Portátil premium con pantalla InfinityEdge 4K, procesador Intel Core i7 y diseño ultradelgado.',
    images: [
      '/placeholder.svg?height=600&width=600',
      '/placeholder.svg?height=600&width=600',
      '/placeholder.svg?height=600&width=600',
      '/placeholder.svg?height=600&width=600',
    ],
    specs: [
      { label: 'Procesador', value: 'Intel Core i7-13700H' },
      { label: 'RAM', value: '16GB DDR5' },
      { label: 'GPU', value: 'NVIDIA RTX 4050' },
      { label: 'Pantalla', value: '15.6" 4K OLED' },
    ],
    rating: 4.6,
    reviews: 543,
    inStock: true,
  },
  {
    id: '7',
    name: 'Apple Watch Series 9',
    price: 429,
    category: 'Wearables',
    description:
      'Smartwatch avanzado con pantalla siempre activa, sensor de salud y GPS de doble frecuencia.',
    images: [
      '/placeholder.svg?height=600&width=600',
      '/placeholder.svg?height=600&width=600',
      '/placeholder.svg?height=600&width=600',
      '/placeholder.svg?height=600&width=600',
    ],
    specs: [
      { label: 'Chip', value: 'S9 SiP' },
      { label: 'Pantalla', value: 'Always-On Retina' },
      { label: 'Batería', value: 'Hasta 18 horas' },
      { label: 'Resistencia', value: 'WR50 + IP6X' },
    ],
    rating: 4.8,
    reviews: 1876,
    inStock: true,
  },
  {
    id: '8',
    name: 'LG C3 OLED 65"',
    price: 2199,
    category: 'TVs',
    description: 'TV OLED 4K con procesador α9 Gen6 AI, HDMI 2.1 y soporte para Dolby Vision IQ.',
    images: [
      '/placeholder.svg?height=600&width=600',
      '/placeholder.svg?height=600&width=600',
      '/placeholder.svg?height=600&width=600',
      '/placeholder.svg?height=600&width=600',
    ],
    specs: [
      { label: 'Tamaño', value: '65 pulgadas' },
      { label: 'Resolución', value: '4K OLED' },
      { label: 'Procesador', value: 'α9 Gen6 AI' },
      { label: 'Refresh Rate', value: '120Hz' },
    ],
    rating: 4.9,
    reviews: 432,
    inStock: true,
  },
]
